-- This script was generated by the Schema Diff utility in pgAdmin 4
-- For the circular dependencies, the order in which Schema Diff writes the objects is not very sophisticated
-- and may require manual changes to the script to ensure changes are applied in the correct order.
-- Please report an issue for any failure with the reproduction steps.

CREATE POLICY "Prohibir la inserción de nuevas plantillas a todos"
    ON public."Plantillas"
    AS PERMISSIVE
    FOR INSERT
    TO public
    WITH CHECK (false);


CREATE POLICY "Permitir la lectura a usuarios autenticados"
    ON public."Plantillas"
    AS PERMISSIVE
    FOR SELECT
    TO public
    USING ((auth.role() = 'authenticated'::text));

CREATE POLICY "Prohibir el borrado de plantillas a todos los usuarios"
    ON public."Plantillas"
    AS PERMISSIVE
    FOR DELETE
    TO public
    USING (false);

CREATE POLICY "Prohibir la actualización a todos los usuarios"
    ON public."Plantillas"
    AS PERMISSIVE
    FOR UPDATE
    TO public
    USING (false)
    WITH CHECK (false);

CREATE POLICY "Mostrar solo las instancias pertenecientes al usuario"
    ON public."Instancias"
    AS PERMISSIVE
    FOR SELECT
    TO public
    USING ((auth.uid() = id_user));

CREATE POLICY "Prohibir inserción de instancias nuevas"
    ON public."Instancias"
    AS PERMISSIVE
    FOR INSERT
    TO public
    WITH CHECK (false);
