-- This script was generated by the Schema Diff utility in pgAdmin 4
-- For the circular dependencies, the order in which Schema Diff writes the objects is not very sophisticated
-- and may require manual changes to the script to ensure changes are applied in the correct order.
-- Please report an issue for any failure with the reproduction steps.

CREATE TABLE IF NOT EXISTS public."Plantillas"
(
    id bigint NOT NULL GENERATED BY DEFAULT AS IDENTITY ( INCREMENT 1 START 1 MINVALUE 1 MAXVALUE 9223372036854775807 CACHE 1 ),
    nombre character varying COLLATE pg_catalog."default" NOT NULL,
    created_at timestamp with time zone DEFAULT now(),
    CONSTRAINT "Plantillas_pkey" PRIMARY KEY (id)
)

TABLESPACE pg_default;

ALTER TABLE IF EXISTS public."Plantillas"
    OWNER to postgres;

ALTER TABLE IF EXISTS public."Plantillas"
    ENABLE ROW LEVEL SECURITY;

GRANT ALL ON TABLE public."Plantillas" TO anon;

GRANT ALL ON TABLE public."Plantillas" TO authenticated;

GRANT ALL ON TABLE public."Plantillas" TO postgres;

GRANT ALL ON TABLE public."Plantillas" TO service_role;

COMMENT ON TABLE public."Plantillas"
    IS 'Plantillas disponibles para instanciar';

CREATE TABLE IF NOT EXISTS public."Instancias"
(
    id bigint NOT NULL GENERATED BY DEFAULT AS IDENTITY ( INCREMENT 1 START 1 MINVALUE 1 MAXVALUE 9223372036854775807 CACHE 1 ),
    nombre character varying COLLATE pg_catalog."default" NOT NULL,
    created_at timestamp with time zone DEFAULT now(),
    id_user uuid NOT NULL,
    id_plantilla bigint NOT NULL,
    CONSTRAINT "Instancias_pkey" PRIMARY KEY (id),
    CONSTRAINT "Instancias_id_plantilla_fkey" FOREIGN KEY (id_plantilla)
        REFERENCES public."Plantillas" (id) MATCH SIMPLE
        ON UPDATE NO ACTION
        ON DELETE NO ACTION,
    CONSTRAINT "Instancias_id_user_fkey" FOREIGN KEY (id_user)
        REFERENCES auth.users (id) MATCH SIMPLE
        ON UPDATE NO ACTION
        ON DELETE NO ACTION
)

TABLESPACE pg_default;

ALTER TABLE IF EXISTS public."Instancias"
    OWNER to postgres;

ALTER TABLE IF EXISTS public."Instancias"
    ENABLE ROW LEVEL SECURITY;

GRANT ALL ON TABLE public."Instancias" TO anon;

GRANT ALL ON TABLE public."Instancias" TO authenticated;

GRANT ALL ON TABLE public."Instancias" TO postgres;

GRANT ALL ON TABLE public."Instancias" TO service_role;

COMMENT ON TABLE public."Instancias"
    IS 'Instancias generadas pertenecientes a un usuario';
