-- This script was generated by the Schema Diff utility in pgAdmin 4
-- For the circular dependencies, the order in which Schema Diff writes the objects is not very sophisticated
-- and may require manual changes to the script to ensure changes are applied in the correct order.
-- Please report an issue for any failure with the reproduction steps.

CREATE POLICY "Permitir inserción de nuevas instancias"
    ON public."Instancias"
    AS PERMISSIVE
    FOR INSERT
    TO public
    WITH CHECK ((auth.uid() = id_user));


CREATE POLICY "Permitir actualizar una instancia"
    ON public."Instancias"
    AS PERMISSIVE
    FOR UPDATE
    TO public
    USING ((auth.uid() = id_user))
    WITH CHECK ((auth.uid() = id_user));


DROP POLICY IF EXISTS "Prohibir inserción de instancias nuevas" ON public."Instancias";

DROP POLICY IF EXISTS "Prohibir el borrado de plantillas a todos los usuarios" ON public."Plantillas";

DROP POLICY IF EXISTS "Prohibir la inserción de nuevas plantillas a todos" ON public."Plantillas";

DROP POLICY IF EXISTS "Prohibir la actualización a todos los usuarios" ON public."Plantillas";
